---
title: "Compare condition data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Compare condition data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
devtools::load_all()
```

This vignette compares fish condition data produced with the `NEesp2::species_condition` function to the condition data in the `ecodata` package.

A function to plot the two condition data sets for each species:
```{r}
plt_species <- function(data, species) {
  ecodata::condition |>
  dplyr::filter(Var == species) |>
  dplyr::mutate(source = "ecodata") |>
  dplyr::bind_rows(
    data |>
  dplyr::filter(Var == species) |>
      dplyr::mutate(source = "new")
  ) |>
  ggplot2::ggplot(ggplot2::aes(
    x = Time,
    y = Value,
    color = EPU,
    shape = source
  )) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::theme_bw() +
  ggplot2::ggtitle(paste(species, "condition comparison"))
}
```

## Create data with`NEesp2::species_condition` 
```{r, echo = TRUE}
all_condition <- readRDS(here::here("data-raw/condition.rds"))$survdat |>
  NEesp2::species_condition(
    LWparams = NEesp2::LWparams,
    species.codes = NEesp2::species.codes,
    output = "soe"
  )
```

## Compare data

```{r, results = "asis"}
for(i in unique(ecodata::condition$Var)) {
  res <- knitr::knit_child(
    input = here::here("data-raw/scripts/child.Rmd"),
    quiet = TRUE
  )
  cat(res, sep = "\n\n")
}
```

## Assess deviations
```{r}
full_data <- ecodata::condition |>
  dplyr::rename(ecodata_value = Value) |>
  dplyr::full_join(
    all_condition |>
      dplyr::rename(new_value = Value)
  )

dat <- full_data |>
  dplyr::mutate(dev_squared = (ecodata_value - new_value)^2) |>
  dplyr::group_by(Time, EPU) |>
  dplyr::summarise(sum_sq_deviation = sum(dev_squared, na.rm = TRUE)) 

dat |>
  dplyr::filter(EPU %in% c("GOM", "GB", "MAB")) |>
  ggplot2::ggplot(ggplot2::aes(x = Time,
                               y = sum_sq_deviation,
                               color = EPU)) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::theme_bw() +
  ggplot2::ggtitle("Sum of squared deviations between ecodata and new condition data")

dat |>
  dplyr::filter(EPU %in% c("GOM", "GB", "MAB"),
                sum_sq_deviation > 0) |>
  # dplyr::arrange(sum_sq_deviation) |>
  knitr::kable()
```

Looking by species:
```{r}
dat <- full_data |>
  dplyr::mutate(dev_squared = (ecodata_value - new_value)^2) |>
  dplyr::group_by(Time, Var) |>
  dplyr::summarise(sum_sq_deviation = sum(dev_squared, na.rm = TRUE)) 

dat |>
  dplyr::filter(sum_sq_deviation > 0) |>
  knitr::kable()

dat <- full_data |>
  dplyr::mutate(dev_squared = (ecodata_value - new_value)^2) |>
  dplyr::group_by(Var) |>
  dplyr::summarise(sum_sq_deviation = sum(dev_squared, na.rm = TRUE)) 

dat |>
  dplyr::filter(sum_sq_deviation > 0) |>
  dplyr::arrange(sum_sq_deviation) |>
  knitr::kable()

```