---
title: ""
geometry: margin=0.5in
output: 
  officedown::rdocx_document
params:
  widths: !r c(0.9, 0.75, 3.15, 3.2)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
here::i_am("06_docs/bsb_table_test.Rmd")
```

```{r}
data <- readxl::read_excel("table_template.xlsx") |>
  janitor::clean_names() |>
  dplyr::mutate(figure =  paste0("../05_images/", time_series)) |>
  dplyr::select(-time_series)
```


```{r}
small_dat <- data |>
  dplyr::mutate(figure = NA) |>
  dplyr::select(-c(w, h)) |>
  dplyr::rename(time_series = figure)

colnames(small_dat) <- colnames(small_dat) |>
  stringr::str_replace_all("_", " ") |>
  stringr::str_to_title()
```

```{r}
flextable::set_flextable_defaults(font.family = "Arial",
                                  font.size = 10)
tbl <- flextable::flextable(small_dat) 
tbl <- flextable::width(tbl, j = 1:4, width = params$widths)
tbl <- flextable::theme_box(tbl)
```


```{r}
for(i in 1:nrow(small_dat)){
  tbl <- flextable::compose(tbl,
                          i = i,
                          j = 4,
                          value = flextable::as_paragraph(
                            flextable::as_image(src = data$figure[i],
                                                width = data$w[i],
                                                height = data$h[i],
                                                unit = "in",
                                                guess_size = FALSE)))
}

tbl <- flextable::align(tbl, i = 1, j = 1:4, align = "center", part = "header")
tbl <- flextable::align(tbl, i = 1:nrow(small_dat), j = 4, align = "center")

tbl
```
