
#' Calculate Swept Area Biomass
#' 
#' This function calculates swept area biomass
#' 
#' @param ... passed to `survdat::calc_swept_area()`. Parameters here: https://noaa-edab.github.io/survdat/reference/calc_swept_area.html
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @return a data table 'swept_area'


# to use EPU shapefile run code below prior to function and set parameters areaPolygon=area and areaDescription="EPU":
#area <- sf::st_read(dsn = system.file("extdata","EPU.shp",package="survdat"),quiet=T) 
create_swept_area <- function(...) { 
  swept_area <- survdat::calc_swept_area(...) %>%
    dplyr::select(.data$YEAR, .data$SVSPP, .data$tot.biomass, .data$tot.bio.var, .data$tot.bio.SE) %>%
    dplyr::rename(swept_area_biomass = .data$tot.biomass, 
                  variance = .data$tot.bio.var,
                  se = .data$tot.bio.SE) %>%
    dplyr::mutate(sd = stats::sd(.data$swept_area_biomass, na.rm = TRUE),
                  INDICATOR_UNITS = "numberstow-1") %>%
    tidyr::pivot_longer(cols = c("swept_area_biomass")) %>%
    dplyr::rename(INDICATOR_NAME = .data$name,
                  DATA_VALUE = .data$value)
  
  return(swept_area)
}


#' Calculate Stratified Mean Biomass
#' 
#' This function calculates stratified mean biomass
#' 
#' @param ... passed to `survdat::calc_stratified_mean()`. Parameters here: https://noaa-edab.github.io/survdat/reference/calc_stratified_mean.html
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @return a data table 'strat_mean'

# to use EPU shapefile run code below prior to function and set parameters areaPolygon=area and areaDescription="EPU":
#area <- sf::st_read(dsn = system.file("extdata","EPU.shp",package="survdat"),quiet=T) 
create_stratified_mean <- function(...) { 
  strat_mean <- survdat::calc_stratified_mean(...) %>%
    dplyr::select(.data$YEAR, .data$SEASON, .data$SVSPP, .data$strat.biomass, .data$biomass.var, .data$biomass.SE) %>%
    dplyr::rename(strat_mean_biomass = .data$strat.biomass, 
                  variance = .data$biomass.var, 
                  se = .data$biomass.SE) %>%
    dplyr::mutate(sd = stats::sd(.data$strat_mean_biomass, na.rm = TRUE),
                  INDICATOR_UNITS = "kgtow-1") %>%
    tidyr::pivot_longer(cols = c("strat_mean_biomass")) %>%
    dplyr::rename(INDICATOR_NAME = .data$name,
                  DATA_VALUE = .data$value)
  
  
  return(strat_mean)
}


#' Calculate Species Range
#'
#' @param data data table. NEFSC survey data generated by 'survdat::get_survdat_data(channel)'
#' @param species data table. NEFSC species data generated by 'survdat::get_species(channel)'
#' @return a data frame
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @export

species_range <- function(data, species) {
  
  
  #filter surveyData to year, season, lat, lon, and species code  
  survdat_data <- data %>%
    dplyr::select(.data$SVSPP, .data$YEAR, .data$SEASON, .data$LAT, .data$LON)
  
  #get species names, filter to species code, scientific + common name
  species_data <- species$data %>%
    tidyr::drop_na(.data$SVSPP) %>%
    dplyr::select (.data$SVSPP, .data$SCINAME, .data$COMNAME) 
  
  #join survdat df with species df grouping by species code
  join <- dplyr::full_join(survdat_data, species_data %>%
                             dplyr::group_by(.data$SVSPP)) 
  
  ##min/max lat/lon for all tows in fall and spring for each year
  all_tows <- join %>%
    dplyr::group_by(.data$YEAR, .data$SEASON) %>%
    dplyr::summarise(min_lat = min(.data$LAT),
                     max_lat = max(.data$LAT),
                     min_lon = min(.data$LON),
                     max_lon = max(.data$LON)) %>%
    tidyr::pivot_longer(cols = c("min_lat", "max_lat", "min_lon", "max_lon")) %>% 
    dplyr::rename(indicator_name = .data$name,
                  indicator_value = .data$value) %>%
    dplyr::ungroup() 
  
  all_tows$species <- "ALL" 
  all_tows$SVSPP <- 0
  
  
  ##min/max/range grouped by species and species code
  all_species <- join %>%
    dplyr::group_by(.data$YEAR, .data$SEASON, .data$SVSPP, .data$COMNAME) %>%
    dplyr::summarise(min_lat = min(.data$LAT),
                     max_lat = max(.data$LAT),
                     min_lon = min(.data$LON),
                     max_lon = max(.data$LON),
    ) %>%
    dplyr::mutate(range_lat = .data$max_lat - .data$min_lat,
                  range_lon = .data$max_lon - .data$min_lon) %>%
    tidyr::pivot_longer(cols = c("min_lat", "max_lat", "min_lon", "max_lon", "range_lat", "range_lon")) %>%
    dplyr::rename(indicator_name = .data$name,
                  indicator_value = .data$value,
                  species = .data$COMNAME) %>%
    dplyr::ungroup()
  
  ##join all_tows and all_species
  range <- rbind(all_tows, all_species) %>%
    dplyr::rename(INDICATOR_NAME = .data$indicator_name,
                  DATA_VALUE = .data$indicator_value,
                  SPECIES = .data$species) %>%
    dplyr::mutate(INDICATOR_UNITS = "degrees")
  return(range)
} 
  