

#' Create species condition indicator
#'
#' This function calculates species condition from a survdat data pull. 
#' Methods derived from Laurel Smith (https://github.com/Laurels1/Condition/blob/master/R/RelConditionEPU.R)
#' 
#' @param data data table. NEFSC survey data generated by 'survdat::get_survdat_data(channel, getBio = T, getLengths = T)'
#' @param LWparams L-W parameters from Wigley et al. 2003 from NEesp2::LWparams
#' @param species.codes data table. Species codes and names from NEesp2::species.codes 
#' @importFrom magrittr %>%
#' @return Returns R object `condition`, a data frame of species condition by EPU with scale.
#' @export

species_condition <- function(data, 
                               LWparams = NEesp2::LWparams, 
                               species.codes = NEesp2::species.codes,
                              by_EPU = TRUE) {

  if(by_EPU) {
    survey.data <- data %>% 
      dplyr::left_join(NEesp2::strata_epu_key)
  } else {
    survey.data <- data |>
      dplyr::mutate(EPU = "UNIT")
  }

  
  #Change sex = NA to sex = 0
  fall <- survey.data %>% 
    dplyr::filter(SEASON == 'FALL') %>% 
    dplyr::mutate(sex = dplyr::if_else(is.na(SEX), '0', as.character(SEX)))
  
  # filter LWparams to fall only, add in male/female if data is "combined"
  LWfall <- LWparams %>% 
    dplyr::filter(SEASON == 'FALL')
  
  add_sexes <- LWfall |>
    dplyr::group_by(SpeciesName) |>
    dplyr::mutate(count = dplyr::n()) |>
    dplyr::filter(count == 1) |>
    dplyr::ungroup() |>
    dplyr::select(-Gender) |>
    dplyr::full_join(tibble::tibble(count = 1,
                                    Gender = c("Male", "Female")),
                     relationship = "many-to-many") |>
    dplyr::select(-count)
  
  new_dat <- dplyr::bind_rows(LWfall, add_sexes) |>
    dplyr::arrange(SpeciesName)
  
  #Add SEX for Combined gender back into Wigley at all data (loses 4 Gender==Unsexed):
  LWpar_sexed <- new_dat |>
    dplyr::mutate(sex = dplyr::case_when(Gender == "Combined" | Gender == "Unsexed" ~ as.character(0),
                                         Gender == "Male" ~ as.character(1),
                                         Gender == "Female" ~ as.character(2),
                                         TRUE ~ NA))
   
  LWpar_spp <- LWpar_sexed %>% 
    dplyr::mutate(SVSPP = as.numeric(LW_SVSPP))
  
  #Join survdat data with LW data
  mergedata <- dplyr::left_join(fall, LWpar_spp, by= c('SEASON', 'SVSPP', 'sex'))
  
  #filters out values without losing rows with NAs:
  mergewt <- dplyr::filter(mergedata, is.na(INDWT) | INDWT<900)
  mergewtno0 <- dplyr::filter(mergewt, is.na(INDWT) | INDWT>0.004)
  mergelenno0 <- dplyr::filter(mergewtno0, is.na(LENGTH) | LENGTH>0)
  mergelen <- dplyr::filter(mergelenno0, !is.na(LENGTH))
  mergeindwt <- dplyr::filter(mergelen, !is.na(INDWT))
  mergeLW <- dplyr::filter(mergeindwt, !is.na(lna))
  # would like to update this -- not sure why the code below does not reproduce the same results
  # mergeLW <- mergedata |>
  #   dplyr::filter(!is.na(LENGTH),
  #                 !is.na(INDWT),
  #                 !is.na(lna),
  #                 INDWT < 900 | INDWT > 0.004,
  #                 LENGTH > 0)
  
  ###########################################
  ### Calculate species condition ###
  
  condcalc <- dplyr::mutate(mergeLW,
                            predwt = (exp(lna))*LENGTH^b,
                            RelCond = INDWT/predwt) |>
    dplyr::filter(is.na(RelCond) | RelCond<300) %>%
    dplyr::group_by(SVSPP, SEX) %>%
    dplyr:: mutate(mean = mean(RelCond), sd = sd(RelCond)) |>
    dplyr::ungroup() |>
    # might want to update this outlier removal eventually
    dplyr::filter(RelCond < (mean+(2*sd)) & RelCond > (mean-(2*sd))) |>
    dplyr::filter(is.na(sex) | sex != 4) %>% 
    dplyr::mutate(sexMF = sex)
  
  cond.epu <- dplyr::left_join(condcalc, species.codes, by= c('SVSPP'))

  #Summarize annually by EPU 
  condition <- cond.epu %>% 
    dplyr::group_by(Species, EPU, YEAR) %>% 
    dplyr::summarize(MeanCond = mean(RelCond), 
                     nCond = dplyr::n()
    ) |>
    dplyr::ungroup() |>
    dplyr::filter(nCond >= 3) %>% 
    dplyr::add_count(Species, EPU) %>% 
    dplyr::filter(n >= 20) %>% 
    dplyr::select(Species, EPU, YEAR, MeanCond, nCond) %>%
    dplyr::group_by(Species, EPU) |>
    dplyr::mutate(sd = sd(MeanCond, na.rm = TRUE),
                  variance = var(MeanCond, na.rm = TRUE),
                  INDICATOR_NAME = "mean condition") %>%
    dplyr::rename(DATA_VALUE = MeanCond) %>%
    dplyr::ungroup()
  
  return(condition)
}



