

## Pull survdat data
# channel <- dbutils::connect_to_database("NEFSC_USERS","SOWEN")
# data <- survdat::get_survdat_data(channel)


## Calculate Swept Area Biomass

#' @param surveyData data table. NEFSC survey data generated by 'get_survdat_data.R'
#' @param areaPolygon sf object or character string. Default = "NEFSC strata". To use any other shapefile, the shapefile must be read in as an sf object and the areaDescription argument must be specified.
#' @param areaDescription  character String. Column name from areaPolygon that contains the strata designations.
#' @param filterByArea numeric vector. Set of areas to subset from the areaDescription of the areaPolygon
#' @param filterBySeason character string. Which seasons of the surveyData should be included. Choices include "SPRING", "FALL", or "all".
#' @param groupDescription character string. Column of prepData which contains the groups (e.g. "SVSPP") on which the means are based.
#' @param filterByGroup character or numeric vector. Set of groups to subset from groupDescription. The default "all" will calculate means for all groups.
#' @param mergesexFlag boolean. Logical value to merge sexed species such as dogfish.
#' @param tidy boolean. Return output in long format (Default = F).
#' @param q data frame. Table of survey catchabilities with a column corresponding to groupDescription and a column of catchabilities. If NULL, assumes a q of 1 for each groupDescription (Minimum swept area estimates).
#' @param a numeric. The average swept area of the trawl. Default value is the swept area of a standard NOAA Ship Albatross IV tow.
#' @return a data table 

# to use EPU shapefile run code below prior to function and set parameters areaPolygon=area and areaDescription="EPU":
#area <- sf::st_read(dsn = system.file("extdata","EPU.shp",package="survdat"),quiet=T) 
`%>%` <- magrittr::`%>%`

calc_swept_area <- function(surveyData, areaPolygon = 'NEFSC strata',
                            areaDescription = 'STRATA', filterByArea = "all",
                            filterBySeason, groupDescription = "SVSPP",
                            filterByGroup = "all", mergesexFlag = T,
                            tidy = F, q = NULL, a = 0.0384) {
  
  #Run stratified mean
  stratmeanData <- calc_stratified_mean(surveyData, areaPolygon, areaDescription,
                                        filterByArea, filterBySeason,
                                        groupDescription, filterByGroup,
                                        mergesexFlag, returnPrepData = T)
  
  #Calculate total biomass/abundance estimates
  message("Calculating Swept Area Estimate  ...")
  sweptareaData <- survdat:::swept_area(prepData = stratmeanData$prepData,
                                        stratmeanData = stratmeanData$stratmeanData,
                                        q = q, areaDescription = areaDescription,
                                        groupDescription = groupDescription)
  
  #create tidy data set
  if(tidy){
    message("Tidying data  ...")
    tidyData <- data.table::melt.data.table(sweptareaData, id.vars = c('YEAR',
                                                                       groupDescription),
                                            measure.vars = c('strat.biomass',
                                                             'biomass.var',
                                                             'strat.abund',
                                                             'abund.var',
                                                             'tot.biomass',
                                                             'tot.bio.var',
                                                             'tot.abundance',
                                                             'tot.abund.var'))
    tidyData[variable == 'strat.biomass', units := 'kg tow^-1']
    tidyData[variable == 'biomass.var',   units := '(kg tow^-1)^2']
    tidyData[variable == 'strat.abund',   units := 'number']
    tidyData[variable == 'abund.var',     units := 'numbers^2']
    tidyData[variable == 'tot.biomass',   units := 'kg']
    tidyData[variable == 'tot.bio.var',   units := 'kg^2']
    tidyData[variable == 'tot.abundance', units := 'number']
    tidyData[variable == 'tot.abund.var', units := 'numbers^2']
    
    sweptareaData <- tidyData
  }
  
  sweptareaData[]
  
  return(sweptareaData)
}


## Calculate Stratified Mean Biomass

#' @param surveyData data table. NEFSC survey data generated by 'get_survdat_data.R'
#' @param areaPolygon sf object or character string. Default = "NEFSC strata". To use any other shapefile, the shapefile must be read in as an sf object and the areaDescription argument must be specified.
#' @param areaDescription  character String. Column name from areaPolygon that contains the strata designations.
#' @param filterByArea numeric vector. Set of areas to subset from the areaDescription of the areaPolygon
#' @param filterBySeason character string. Which seasons of the surveyData should be included. Choices include "SPRING", "FALL", or "all".
#' @param groupDescription character string. Column of prepData which contains the groups (e.g. "SVSPP") on which the means are based.
#' @param filterByGroup character or numeric vector. Set of groups to subset from groupDescription. The default "all" will calculate means for all groups.
#' @param mergesexFlag boolean. Logical value to merge sexed species such as dogfish.
#' @param tidy boolean. Return output in long format (Default = F).
#' @param returnPrepData boolean. Return both stratmeanData and prepData as a list object. The default (F) returns only the stratmeanData as a data.table.
#' @return a data table or list object (if returnPrepData = T)

# to use EPU shapefile run code below prior to function and set parameters areaPolygon=area and areaDescription="EPU":
#area <- sf::st_read(dsn = system.file("extdata","EPU.shp",package="survdat"),quiet=T) 
`%>%` <- magrittr::`%>%`

calc_stratified_mean <- function(surveyData, areaPolygon = 'NEFSC strata',
                                 areaDescription = 'STRATA', filterByArea = "all",
                                 filterBySeason, groupDescription = "SVSPP",
                                 filterByGroup = "all", mergesexFlag = T,
                                 tidy = F, returnPrepData = F) {
  
  # Use original stratified design and built-in shapefile
  if(!is(areaPolygon, 'sf')) {
    if (is.character(areaPolygon)) { # not sf but a string
      if(areaPolygon == 'NEFSC strata') {
        poststratFlag <- F
      } else {
        message("areaPolygon currently only takes \"NEFSC strata\" as character string option")
        stop("areaPolygon incorrectly defined")
      }
    } else { # not sf and not a string
      message("areaPolygon must be an sf object. For example")
      message("areaPolygon <- sf::st_read(dsn = \"shapefile.shp\"")
      stop("areaPolygon incorrectly defined")
      
    }
  } else {
    poststratFlag <- T
  }
  
  #Run stratification prep
  message("Prepping data ...")
  prepData <- survdat:::strat_prep(surveyData, areaPolygon, areaDescription,
                                   filterByArea, filterBySeason)
  
  #Calculate stratified mean
  message("Calculating Stratified Mean  ...")
  #Check if calculating mean base on all station or by season
  if(filterBySeason[1] == "all"){seasonFlag <- F}else{seasonFlag <- T}
  
  stratmeanData <- survdat:::strat_mean(prepData, groupDescription, filterByGroup,
                                        mergesexFlag, seasonFlag = seasonFlag,
                                        areaDescription, poststratFlag)
  
  # create tidy data
  if(tidy){
    message("Tidying data  ...")
    tidyData <- data.table::melt.data.table(stratmeanData, id.vars = c('YEAR',
                                                                       groupDescription,
                                                                       'SEASON'),
                                            measure.vars = c('strat.biomass',
                                                             'biomass.var',
                                                             'biomass.SE',
                                                             'strat.abund',
                                                             'abund.var',
                                                             'abund.SE'))
    tidyData[variable == 'strat.biomass', units := 'kg tow^-1']
    tidyData[variable == 'biomass.var',   units := '(kg tow^-1)^2']
    tidyData[variable == 'biomass.SE',    units := 'kg tow^-1']
    tidyData[variable == 'strat.abund',   units := 'number tow^-1']
    tidyData[variable == 'abund.var',     units := '(numbers tow^-1)^2']
    tidyData[variable == 'abund.SE',      units := 'kg tow^-1']
    stratmeanData <- tidyData
  }
  
  if(returnPrepData) stratmeanData <- list(stratmeanData = stratmeanData,
                                           prepData = prepData)
  
  return(stratmeanData[])
}


## Calculate Species Condition (weight/length^3)

#' @param data  A data frame from `allfh`.
#' @return a data frame
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @export
`%>%` <- magrittr::`%>%`

data <- get(load(here::here("data-raw/allfh.RData")))

species_condition <- function(data) {
  condition <- data %>%
    dplyr::filter(
     is.na(.data$pdlen) == FALSE,
     is.na(.data$pdwgt) == FALSE
   ) %>%
    dplyr::select(.data$pdlen, .data$pdwgt, .data$season, .data$geoarea, .data$pdcomnam, .data$year) %>%
    dplyr::distinct() %>% # remove duplicates
    dplyr::group_by(.data$geoarea, .data$season) %>%
    dplyr::mutate(n_fish = length(.data$pdlen)) %>%
    dplyr::mutate(condition = .data$pdwgt/(.data$pdlen)^3) %>%
    dplyr::rename(region = .data$geoarea, species = .data$pdcomnam, length = .data$pdlen, weight = .data$pdwgt) %>%
    dplyr::filter(.data$n_fish > 10) # only region-season with >10 fish 
  
  return(condition)
} 


#' Create a table of diet data
#'
#' @param data A data frame from `allfh`.
#' @return A `DT::datatable` or a `knitr::kable`
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @export
`%>%` <- magrittr::`%>%`

data <- get(load(here::here("data-raw/allfh.RData")))

diet <- function(data) {
  if (nrow(data) > 0) {
    normalized <- data %>%
      dplyr::filter(.data$pyamtw > 0) %>%
      
      # only look at season/year combinations with >20 predator samples
      dplyr::group_by(.data$year, .data$season, .data$geoarea) %>%
      dplyr::mutate(n_predators = .data$pdcomnam %>%
                      unique() %>%
                      length()) %>%
      dplyr::filter(.data$n_predators > 20)
    
    if (length(normalized$n_predators) > 1) {
      normalized <- normalized %>%
        dplyr::group_by(.data$year, .data$season, .data$geoarea, .data$gensci) %>%
        dplyr::summarise(total_weight = sum(.data$pyamtw)) %>%
        dplyr::mutate(proportion = .data$total_weight / sum(.data$total_weight))
      
      normalized$gensci <- stringr::str_replace(normalized$gensci, " ", "_")
      
      # group low abundance prey as "other"
      groups <- normalized %>%
        dplyr::group_by(.data$year, .data$season, .data$geoarea, .data$gensci) %>%
        dplyr::summarise(max_prop = max(.data$proportion)) %>%
        dplyr::filter(.data$max_prop > 0.05)
      
      groups <- groups$gensci %>%
        unique()
      
      rows <- match(normalized$gensci, groups) %>%
        is.na() %>%
        which()
      
      normalized[rows, "gensci"] <- "OTHER"
      
      # re-group proportions with new "other" category
      normalized <- normalized %>%
        dplyr::group_by(.data$year, .data$season, .data$geoarea, .data$gensci) %>%
        dplyr::summarise(prop2 = sum(.data$proportion))
      
      # summary table
      table <- normalized %>%
        dplyr::group_by(.data$gensci, .data$season, .data$geoarea, .data$year) %>%
        dplyr::filter(sum(.data$prop2) > 0) %>%
        dplyr::group_by(.data$gensci, .data$season, .data$geoarea) %>%
        dplyr::rename(prey_name = 'gensci', region = 'geoarea') %>%
        dplyr::summarise(
          mean_proportion = paste(mean(.data$prop2) %>% round(digits = 3),
                                  " +- ",
                                  stats::sd(.data$prop2) %>% round(digits = 3),
                                  " (", length(.data$prop2), ") ",
                                  sep = ""
          ),
          
          range_proportion = paste(min(.data$prop2) %>% round(digits = 3),
                                   max(.data$prop2) %>% round(digits = 3),
                                   sep = " - "
          )
        )
    } else {
      print("NOT ENOUGH DATA")
    }
  } else {
    print("NO DATA")
  }
}

#' Calculate Species Range
#'
#' @param surveyData data table. NEFSC survey data generated by 'survdat::get_survdat_data(channel)'
#' @param species data table. NEFSC species data generated by 'survdat::get_species(channel)'
#' @return a data frame
#' @importFrom magrittr %>%
#' @export
`%>%` <- magrittr::`%>%`
            
species_range <- function(surveyData, species) {
  
  #filter surveyData to year, season, lat, lon, and species code  
  survdat_data <- surveyData$survdat %>%
    dplyr::select(SVSPP, YEAR, SEASON, LAT, LON)
  
  #get species names, filter to species code, scientific + common name
  species_data <- species$data %>%
    tidyr::drop_na(SVSPP) %>%
    dplyr::select (SVSPP, SCINAME, COMNAME) 
  
  #join survdat df with species df grouping by species code
  join <- dplyr::full_join(survdat_data, species_data %>%
                             dplyr::group_by(SVSPP)) 
  
  ##min/max lat/lon for all tows in fall and spring for each year
  all_tows <- join %>%
    dplyr::group_by(YEAR, SEASON) %>%
    dplyr::summarise(min_lat = min(LAT),
                     max_lat = max(LAT),
                     min_lon = min(LON),
                     max_lon = max(LON)) %>%
    tidyr::pivot_longer(cols = c("min_lat", "max_lat", "min_lon", "max_lon")) %>% 
    dplyr::rename(indicator_name = name,
                  indicator_value = value) %>%
    dplyr::ungroup() 
  
  all_tows$species <- "ALL" 
  all_tows$SVSPP <- 0
  
  
  ##min/max/range grouped by species and species code
  all_species <- join %>%
    dplyr::group_by(YEAR, SEASON, SVSPP, COMNAME) %>%
    dplyr::summarise(min_lat = min(LAT),
                     max_lat = max(LAT),
                     min_lon = min(LON),
                     max_lon = max(LON),
    ) %>%
    dplyr::mutate(range_lat = max_lat - min_lat,
                  range_lon = max_lon - min_lon) %>%
    tidyr::pivot_longer(cols = c("min_lat", "max_lat", "min_lon", "max_lon", "range_lat", "range_lon")) %>%
    dplyr::rename(indicator_name = name,
                  indicator_value = value,
                  species = COMNAME) %>%
    dplyr::ungroup()
  
  ##join all_tows and all_species
  rbind(all_tows, all_species)
} 
  