`%>%` <- magrittr::`%>%`

## Pull survdat data
channel <- dbutils::connect_to_database("NEFSC_USERS","SOWEN")
data <- survdat::get_survdat_data(channel)


## Calculate Swept Area Biomass

#' @param surveyData data table. NEFSC survey data generated by 'get_survdat_data.R'
#' @param areaPolygon sf object or character string. Default = "NEFSC strata". To use any other shapefile, the shapefile must be read in as an sf object and the areaDescription argument must be specified.
#' @param areaDescription  character String. Column name from areaPolygon that contains the strata designations.
#' @param filterByArea numeric vector. Set of areas to subset from the areaDescription of the areaPolygon
#' @param filterBySeason character string. Which seasons of the surveyData should be included. Choices include "SPRING", "FALL", or "all".
#' @param groupDescription character string. Column of prepData which contains the groups (e.g. "SVSPP") on which the means are based.
#' @param filterByGroup character or numeric vector. Set of groups to subset from groupDescription. The default "all" will calculate means for all groups.
#' @param mergesexFlag boolean. Logical value to merge sexed species such as dogfish.
#' @param tidy boolean. Return output in long format (Default = F).
#' @param q data frame. Table of survey catchabilities with a column corresponding to groupDescription and a column of catchabilities. If NULL, assumes a q of 1 for each groupDescription (Minimum swept area estimates).
#' @param a numeric. The average swept area of the trawl. Default value is the swept area of a standard NOAA Ship Albatross IV tow.
#' @return a data table 

# to use EPU shapefile run code below prior to function and set parameters areaPolygon=area and areaDescription="EPU":
area <- sf::st_read(dsn = system.file("extdata","EPU.shp",package="survdat"),quiet=T) 

survdat::calc_swept_area(
  surveyData,
  areaPolygon = "NEFSC strata",
  areaDescription = "STRATA",
  filterByArea = "all",
  filterBySeason,
  groupDescription = "SVSPP",
  filterByGroup = "all",
  mergesexFlag = T,
  tidy = F,
  q = NULL,
  a = 0.0384
)

## Calculate Stratified Mean Biomass

#' @param surveyData data table. NEFSC survey data generated by 'get_survdat_data.R'
#' @param areaPolygon sf object or character string. Default = "NEFSC strata". To use any other shapefile, the shapefile must be read in as an sf object and the areaDescription argument must be specified.
#' @param areaDescription  character String. Column name from areaPolygon that contains the strata designations.
#' @param filterByArea numeric vector. Set of areas to subset from the areaDescription of the areaPolygon
#' @param filterBySeason character string. Which seasons of the surveyData should be included. Choices include "SPRING", "FALL", or "all".
#' @param groupDescription character string. Column of prepData which contains the groups (e.g. "SVSPP") on which the means are based.
#' @param filterByGroup character or numeric vector. Set of groups to subset from groupDescription. The default "all" will calculate means for all groups.
#' @param mergesexFlag boolean. Logical value to merge sexed species such as dogfish.
#' @param tidy boolean. Return output in long format (Default = F).
#' @param returnPrepData boolean. Return both stratmeanData and prepData as a list object. The default (F) returns only the stratmeanData as a data.table.
#' @return a data table or list object (if returnPrepData = T)

# to use EPU shapefile run code below prior to function and set parameters areaPolygon=area and areaDescription="EPU":
area <- sf::st_read(dsn = system.file("extdata","EPU.shp",package="survdat"),quiet=T) 

survdat::calc_stratified_mean(
  surveyData,
  areaPolygon = "NEFSC strata",
  areaDescription = "STRATA",
  filterByArea = "all",
  filterBySeason,
  groupDescription = "SVSPP",
  filterByGroup = "all",
  mergesexFlag = T,
  tidy = F,
  returnPrepData = F
)

## Calculate Species Condition (weight/length^3)

#' @param data  A data frame from `allfh`.
#' @return a data frame
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @export

data <- get(load(here::here("data-raw/allfh.RData")))

condition <- function(x) {
  data %>%
  dplyr::filter(
    is.na(.data$pdlen) == FALSE,
    is.na(.data$pdwgt) == FALSE
  ) %>%
  dplyr::select(.data$pdlen, .data$pdwgt, .data$season, .data$geoarea, .data$pdcomnam, .data$year) %>%
  dplyr::distinct() %>% # remove duplicates
  dplyr::group_by(.data$geoarea, .data$season) %>%
  dplyr::mutate(n_fish = length(.data$pdlen)) %>%
  dplyr::mutate(condition = .data$pdwgt/(.data$pdlen)^3) %>%
  dplyr::rename(region = .data$geoarea, species = .data$pdcomnam, length = .data$pdlen, weight = .data$pdwgt) %>%
  dplyr::filter(.data$n_fish > 10) # only region-season with >10 fish 
} 

            
  
  